export { useGetLists } from './useGetLists'
export { useGetList } from './useGetList'
export { useGetListEntries } from './useGetListEntries'
export { useRemoveListEntry } from './useRemoveListEntry'
// The barrel is the only thing components import from this domain
// (frontend.md → Frontend data fetching).
export { useGetObjects } from './useGetObjects'
export { useGetObject } from './useGetObject'
export { useListRecords } from './useListRecords'
export type { UseListRecordsParams } from './useListRecords'
export { useRecordWindow } from './useRecordWindow'
export { useGetActivity } from './useGetActivity'
export type { ActivityScope } from './useGetActivity'
export { useGetFieldChanges } from './useGetFieldChanges'
export { useGetFieldHistory } from './useGetFieldHistory'
export { useUpdateRecordValue } from './useUpdateRecordValue'
export { useCreateRecord } from './useCreateRecord'
export { useCreateNote } from './useCreateNote'
